=== cpl-kr/cass/Documentation/GUIServer.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="GUI" targetNamespace="GUI"
	elementFormDefault="qualified">
	<xs:element name="GUI">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Version" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="SessionId" type="xs:string" minOccurs="1" maxOccurs="1" />
				<xs:element name="Type" type="GUIType" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="GUIType">
		<xs:choice>
			<xs:element name="InitialGUI" type="InitialGUIType" minOccurs="1" maxOccurs="1" />
			<xs:element name="ChangeGUI" type="ChangeGUIType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Exit" minOccurs="1" maxOccurs="1" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="InitialGUIType">
		<xs:sequence>
			<xs:element name="Windows" type="WindowsType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WindowsType">
		<xs:sequence>
			<xs:element name="Window" type="WindowType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WindowType">
		<xs:sequence>
			<xs:element name="ID" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Position" type="PositionType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Elemente" type="ElementeType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ChangeGUIType">
		<xs:sequence>
			<xs:element name="Operation" type="OperationType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OperationType">
		<xs:choice>
			<xs:element name="AddWindow" type="AddWindowType" minOccurs="1" maxOccurs="1" />
			<xs:element name="AddElement" type="AddElementType" minOccurs="1" maxOccurs="1" />
			<xs:element name="RemoveWindow" type="RemoveWindowType" minOccurs="1" maxOccurs="1" />
			<xs:element name="RemoveElement" type="RemoveElementType" minOccurs="1" maxOccurs="1" />
			<xs:element name="ChangeElement" type="ChangeElementType" minOccurs="1" maxOccurs="1" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="AddWindowType">
		<xs:sequence>
			<xs:sequence>
				<xs:element name="Window" type="WindowType" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AddElementType">
		<xs:sequence>
			<xs:element name="WindowID" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Element" type="ElementType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RemoveWindowType">
		<xs:sequence>
			<xs:element name="WindowID" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RemoveElementType">
		<xs:sequence>
			<xs:element name="WindowID" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="ElementID" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ChangeElementType">
		<xs:sequence>
			<xs:element name="WindowID" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="ElementID" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Operation" type="ElementOperationType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ElementOperationType">
		<xs:choice>
			<xs:element name="ChangeState" type="ChangeStateType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Reload" type="ReloadType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Event" type="Event" minOccurs="1" maxOccurs="1" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="ChangeStateType">
		<xs:sequence>
			<xs:element name="State" type="StateType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReloadType">
		<xs:sequence>
			<xs:element name="View" type="ViewType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Image" type="SourceType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ViewType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Active" />
			<xs:enumeration value="Inactive" />
			<xs:enumeration value="MouseOver" />
			<xs:enumeration value="Pressed" />
			<xs:enumeration value="Dragged" />
			<xs:enumeration value="ActiveDeselected" />
			<xs:enumeration value="ActiveSelected" />
			<xs:enumeration value="ActiveDeselectedMouseOver" />
			<xs:enumeration value="ActiveSelectedMouseOver" />
			<xs:enumeration value="InactiveDeselected" />
			<xs:enumeration value="InactiveSelected" />
			<xs:enumeration value="Focus" />
			<xs:enumeration value="ActiveMouseOver" />
			<xs:enumeration value="FocusMouseOver" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="PositionType">
		<xs:sequence>
			<xs:element name="X-Position" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="Y-Position" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="Width" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="Height" type="xs:integer" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ElementeType">
		<xs:sequence>
			<xs:element name="Element" type="ElementType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ElementType">
		<xs:sequence>
			<xs:element name="ID" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="Ebene" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="Zeichnungsnummer" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="Position" type="PositionType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Elementtyp" type="ElementtypType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Opacity" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="Event" type="Event" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ElementtypType">
		<xs:choice>
			<xs:element name="Content" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Button" type="ButtonType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Select" type="SelectType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Klick" type="KlickType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Slider" type="SliderType" minOccurs="1" maxOccurs="1" />
			<xs:element name="TextInput" type="TextInputType" minOccurs="1" maxOccurs="1" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="SourceType">
		<xs:choice>
			<xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="File" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="HtmlBase64" type="xs:base64Binary" minOccurs="1" maxOccurs="1" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="HtmlInputType">
		<xs:sequence>
			<xs:element name="BeforeBase64" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="AfterBase64" type="xs:string" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ButtonType">
		<xs:sequence>
			<xs:element name="ActiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InactiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="MouseOverImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="PressedImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="StartState" type="StateType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SelectType">
		<xs:sequence>
			<xs:element name="ActiveDeselectedImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="ActiveSelectedImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="ActiveDeselectedMouseOverImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="ActiveSelectedMouseOverImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InactiveDeselectedImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InactiveSelectedImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="StartState" type="StateType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="KlickType">
		<xs:sequence>
			<xs:element name="ActiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InactiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="MouseOverImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="StartState" type="StateType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SliderType">
		<xs:sequence>
			<xs:element name="ActiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InactiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="MouseOverImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="DraggedImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="StartState" type="StateType" minOccurs="1" maxOccurs="1" />
			<xs:element name="X" type="SliderDraggType" minOccurs="0" maxOccurs="1" />
			<xs:element name="Y" type="SliderDraggType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SliderDraggType">
		<xs:sequence>
			<xs:element name="RangePlus" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="RangeMinus" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="StepSize" type="xs:integer" minOccurs="1" maxOccurs="1" />
			<xs:element name="MoveCount" type="xs:integer" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TextInputType">
		<xs:sequence>
			<xs:element name="ActiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InactiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="FocusImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="MouseOverActiveImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="MouseOverFocusImage" type="SourceType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InputActive" type="HtmlInputType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InputInactive" type="HtmlInputType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InputFocus" type="HtmlInputType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InputMouseOverActive" type="HtmlInputType" minOccurs="1" maxOccurs="1" />
			<xs:element name="InputMouseOverFocus" type="HtmlInputType" minOccurs="1" maxOccurs="1" />
			<xs:element name="CharacterCount" type="xs:integer" minOccurs="0" maxOccurs="1" />
			<xs:element name="StartState" type="StateType" minOccurs="1" maxOccurs="1" />
			<xs:element name="Cursor" type="xs:base64Binary" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Event">
		<xs:attribute name="Type" type="EventtypType" use="required" />
		<xs:attribute name="active" type="xs:boolean" use="required" />
	</xs:complexType>
	<xs:simpleType name="StateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Active" />
			<xs:enumeration value="Inactive" />
			<xs:enumeration value="ActiveDeselected" />
			<xs:enumeration value="ActiveSelected" />
			<xs:enumeration value="InactiveDeselected" />
			<xs:enumeration value="InactiveSelected" />
			<xs:enumeration value="Focus" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EventtypType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Entered" />
			<xs:enumeration value="Exited" />
			<xs:enumeration value="Moved" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UrlType">
		<xs:restriction base="xs:string">
			<xs:pattern value="https://[a-zA-Z]*" /> <!-- Hier noch genauer spezifizieren -->
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== cpl-kr/cass/ClapsesyDemo/DemoXml/Demo1/ChangeGUIChangeElementDeselectStateDeselected.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<ChangeGUI>
			<Operation>
				<ChangeElement>
					<WindowID>window2</WindowID>
					<ElementID>elementdeselect1</ElementID>
					<Operation>
						<ChangeState>
							<State>ActiveDeselected</State>
						</ChangeState>
					</Operation>
				</ChangeElement>
			</Operation>
		</ChangeGUI>
	</Type>
</GUI>

=== cpl-kr/cass/ClapsesyDemo/DemoXml/Demo1/ChangeGUIChangeElementEvent.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<ChangeGUI>
			<Operation>
				<ChangeElement>
					<WindowID>window2</WindowID>
					<ElementID>element2</ElementID>
					<Operation>
						<Event Type="Moved" active="true" />
					</Operation>
				</ChangeElement>
			</Operation>
		</ChangeGUI>
	</Type>
</GUI>

=== cpl-kr/cass/CassDemo/DemoXml/Demo1/ChangeGUIAddElementMenu.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<ChangeGUI>
			<Operation>
				<AddElement>
					<WindowID>window2</WindowID>
						<Element>
							<ID>elementklick1-1</ID>
							<Ebene>3</Ebene>
							<Zeichnungsnummer>1</Zeichnungsnummer>
							<Position>
								<X-Position>0</X-Position>
								<Y-Position>530</Y-Position>
								<Width>75</Width>
								<Height>20</Height>
							</Position>
							<Elementtyp>
								<Klick>
									<ActiveImage>
										<URL>http://localhost:8080/CASS/GuiElementSeiten/Klick/Menu1/Menu1-1Active.html</URL>
									</ActiveImage>
									<InactiveImage>
										<URL>http://localhost:8080/CASS/GuiElementSeiten/Klick/Menu1/Menu1-1Inactive.html</URL>
									</InactiveImage>
									<MouseOverImage>
										<URL>http://localhost:8080/CASS/GuiElementSeiten/Klick/Menu1/Menu1-1MouseOver.html</URL>
									</MouseOverImage>
									<StartState>Active</StartState>
								</Klick>
							</Elementtyp>
						</Element>
				</AddElement>
			</Operation>
			<Operation>
				<AddElement>
					<WindowID>window2</WindowID>
						<Element>
							<ID>elementklick1-2</ID>
							<Ebene>3</Ebene>
							<Zeichnungsnummer>2</Zeichnungsnummer>
							<Position>
								<X-Position>0</X-Position>
								<Y-Position>510</Y-Position>
								<Width>75</Width>
								<Height>20</Height>
							</Position>
							<Elementtyp>
								<Klick>
									<ActiveImage>
										<URL>http://localhost:8080/CASS/GuiElementSeiten/Klick/Menu1/Menu1-2Active.html</URL>
									</ActiveImage>
									<InactiveImage>
										<URL>http://localhost:8080/CASS/GuiElementSeiten/Klick/Menu1/Menu1-2Inactive.html</URL>
									</InactiveImage>
									<MouseOverImage>
										<URL>http://localhost:8080/CASS/GuiElementSeiten/Klick/Menu1/Menu1-2MouseOver.html</URL>
									</MouseOverImage>
									<StartState>Active</StartState>
								</Klick>
							</Elementtyp>
						</Element>
				</AddElement>
			</Operation>
		</ChangeGUI>
	</Type>
</GUI>

=== cpl-kr/cass/ClapsesyDemo/DemoXml/Demo2/InitialGUI.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<InitialGUI>
			<Windows>
				<Window>
					<ID>Zeitangabe</ID>
					<Title>Zeitangabe</Title>
					<Position>
						<X-Position>100</X-Position>
						<Y-Position>100</Y-Position>
						<Width>450</Width>
						<Height>150</Height>
					</Position>
					<Elemente>
						<Element>
							<ID>StundeZehnerstelle</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>1</Zeichnungsnummer>
							<Position>
								<X-Position>0</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Ziffer0.html</URL>
								</Content>
							</Elementtyp>
						</Element>
						<Element>
							<ID>StundeEinerstelle</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>2</Zeichnungsnummer>
							<Position>
								<X-Position>50</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Ziffer0.html</URL>
								</Content>
							</Elementtyp>
						</Element>
						<Element>
							<ID>Doppelpunkt1</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>3</Zeichnungsnummer>
							<Position>
								<X-Position>100</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Doppelpunkt.html</URL>
								</Content>
							</Elementtyp>
						</Element>
						<Element>
							<ID>MinuteZehnerstelle</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>4</Zeichnungsnummer>
							<Position>
								<X-Position>150</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Ziffer0.html</URL>
								</Content>
							</Elementtyp>
						</Element>
						<Element>
							<ID>MinuteEinerstelle</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>5</Zeichnungsnummer>
							<Position>
								<X-Position>200</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Ziffer0.html</URL>
								</Content>
							</Elementtyp>
						</Element>
						<Element>
							<ID>Doppelpunkt2</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>6</Zeichnungsnummer>
							<Position>
								<X-Position>250</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Doppelpunkt.html</URL>
								</Content>
							</Elementtyp>
						</Element>
						<Element>
							<ID>SekundeZehnerstelle</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>7</Zeichnungsnummer>
							<Position>
								<X-Position>300</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Ziffer0.html</URL>
								</Content>
							</Elementtyp>
						</Element>
						<Element>
							<ID>SekundeEinerstelle</ID>
							<Ebene>1</Ebene>
							<Zeichnungsnummer>8</Zeichnungsnummer>
							<Position>
								<X-Position>350</X-Position>
								<Y-Position>0</Y-Position>
								<Width>50</Width>
								<Height>100</Height>
							</Position>
							<Elementtyp>
								<Content>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Ziffern/Ziffer0.html</URL>
								</Content>
							</Elementtyp>
						</Element>
					</Elemente>
				</Window>
			</Windows>
		</InitialGUI>
	</Type>
</GUI>

=== cpl-kr/cass/ClapsesyDemo/DemoXml/Demo1/ChangeGUIRemoveElement.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<ChangeGUI>
			<Operation>
				<RemoveElement>
					<WindowID>window2</WindowID>
					<ElementID>element6</ElementID>
				</RemoveElement>
			</Operation>
		</ChangeGUI>
	</Type>
</GUI>

=== cpl-kr/cass/Demo/DemoXml/Demo1/ChangeGUIAddWindow.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<ChangeGUI>
			<Operation>
				<AddWindow>
					<Window>
						<ID>window3</ID>
						<Title>title3</Title>
						<Position>
							<X-Position>300</X-Position>
							<Y-Position>44</Y-Position>
							<Width>270</Width>
							<Height>500</Height>
						</Position>
						<Elemente>
							<Element>
								<ID>element1</ID>
								<Ebene>2</Ebene>
								<Zeichnungsnummer>1</Zeichnungsnummer>
								<Position>
									<X-Position>0</X-Position>
									<Y-Position>0</Y-Position>
									<Width>250</Width>
									<Height>100</Height>
								</Position>
								<Elementtyp>
									<Button>
										<ActiveImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonActive.html</URL>
										</ActiveImage>
										<InactiveImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonInactive.html</URL>
										</InactiveImage>
										<MouseOverImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonMouseOver.html</URL>
										</MouseOverImage>
										<PressedImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonPressed.html</URL>
										</PressedImage>
										<StartState>Active</StartState>
									</Button>
								</Elementtyp>
							</Element>
							<Element>
								<ID>element2</ID>
								<Ebene>2</Ebene>
								<Zeichnungsnummer>2</Zeichnungsnummer>
								<Position>
									<X-Position>0</X-Position>
									<Y-Position>100</Y-Position>
									<Width>250</Width>
									<Height>100</Height>
								</Position>
								<Elementtyp>
									<Select>
										<ActiveDeselectedImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/SelectActiveDeselected.html</URL>
										</ActiveDeselectedImage>
										<ActiveSelectedImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/SelectActiveSelected.html</URL>
										</ActiveSelectedImage>
										<ActiveDeselectedMouseOverImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/SelectActiveDeselectedMouseOver.html</URL>
										</ActiveDeselectedMouseOverImage>
										<ActiveSelectedMouseOverImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/SelectActiveSelectedMouseOver.html</URL>
										</ActiveSelectedMouseOverImage>
										<InactiveDeselectedImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/SelectInactiveDeselected.html</URL>
										</InactiveDeselectedImage>
										<InactiveSelectedImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/SelectInactiveSelected.html</URL>
										</InactiveSelectedImage>
										<StartState>ActiveDeselected</StartState>
									</Select>
								</Elementtyp>
							</Element>
							<Element>
								<ID>element3</ID>
								<Ebene>2</Ebene>
								<Zeichnungsnummer>3</Zeichnungsnummer>
								<Position>
									<X-Position>0</X-Position>
									<Y-Position>200</Y-Position>
									<Width>250</Width>
									<Height>100</Height>
								</Position>
								<Elementtyp>
									<Klick>
										<ActiveImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/KlickActive.html</URL>
										</ActiveImage>
										<InactiveImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/KlickInactive.html</URL>
										</InactiveImage>
										<MouseOverImage>
											<URL>http://localhost:8080/clapsesy/GuiElementSeiten/KlickMouseOver.html</URL>
										</MouseOverImage>
										<StartState>Active</StartState>
									</Klick>
								</Elementtyp>
							</Element>
							<Element>
								<ID>element0</ID>
								<Ebene>1</Ebene>
								<Zeichnungsnummer>1</Zeichnungsnummer>
								<Position>
									<X-Position>0</X-Position>
									<Y-Position>0</Y-Position>
									<Width>250</Width>
									<Height>450</Height>
								</Position>
								<Elementtyp>
									<Content>
										<URL>http://localhost:8080/clapsesy/GuiElementSeiten/Content.html</URL>
									</Content>
								</Elementtyp>
							</Element>
						</Elemente>
					</Window>
				</AddWindow>
			</Operation>
		</ChangeGUI>
	</Type>
</GUI>

=== cpl-kr/cass/ClapsesyDemo/DemoXml/Demo1/ChangeGUIAddElement.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<ChangeGUI>
			<Operation>
				<AddElement>
					<WindowID>window2</WindowID>
					<Element>
						<ID>element6</ID>
						<Ebene>3</Ebene>
						<Zeichnungsnummer>1</Zeichnungsnummer>
						<Position>
							<X-Position>0</X-Position>
							<Y-Position>500</Y-Position>
							<Width>100</Width>
							<Height>50</Height>
						</Position>
						<Elementtyp>
							<Button>
								<ActiveImage>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonActive.html</URL>
								</ActiveImage>
								<InactiveImage>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonInactive.html</URL>
								</InactiveImage>
								<MouseOverImage>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonMouseOver.html</URL>
								</MouseOverImage>
								<PressedImage>
									<URL>http://localhost:8080/clapsesy/GuiElementSeiten/ButtonPressed.html</URL>
								</PressedImage>
								<StartState>Active</StartState>
							</Button>
						</Elementtyp>
					</Element>
				</AddElement>
			</Operation>
		</ChangeGUI>
	</Type>
</GUI>

=== cpl-kr/cass/Demo/DemoXml/Demo1/ChangeGUIChangeElementSelectStateSelected.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GUI xmlns="GUI"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="GUIServer.xsd">
	<Version>1.0.0</Version>
	<SessionId></SessionId>
	<Type>
		<ChangeGUI>
			<Operation>
				<ChangeElement>
					<WindowID>window2</WindowID>
					<ElementID>elementselect1</ElementID>
					<Operation>
						<ChangeState>
							<State>ActiveSelected</State>
						</ChangeState>
					</Operation>
				</ChangeElement>
			</Operation>
		</ChangeGUI>
	</Type>
</GUI>
